### ISSUE TITLE
Github action failing

### ISSUE THREAD

**Issue by jerriclynsjohn** [Borales/actions-yarn#47]
My github action is specifically failing at this step and these are the logs

```bash
##[debug]Evaluating condition for step: 'Build borales/actions-yarn@v[2](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:2).[3](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:3).0'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> ***
##[debug]Result: ***
##[debug]Starting: Build borales/actions-yarn@v2.3.0
Build container for action use: '/home/runner/work/_actions/borales/actions-yarn/v2.3.0/Dockerfile'.
/usr/bin/docker build -t 6f1554:c225bc8523c743e7a0fd46ac072d21be -f "/home/runner/work/_actions/borales/actions-yarn/v2.3.0/Dockerfile" "/home/runner/work/_actions/borales/actions-yarn/v2.3.0"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/6 : FROM node:lts-alpine
  lts-alpine: Pulling from library/node
  2408cc74d12b: Pulling fs layer
  5b80453a567d: Pulling fs layer
  3420de6432e1: Pulling fs layer
  65b54[9](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:9)a28248: Pulling fs layer
  65b549a28248: Waiting
  3420de6432e1: Verifying Checksum
  3420de6432e1: Download complete
  2408cc74d[12](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:12)b: Verifying Checksum
  2408cc74d12b: Download complete
  2408cc74d12b: Pull complete
  65b549a28248: Verifying Checksum
  65b549a28248: Download complete
  5b80453a567d: Verifying Checksum
  5b80453a567d: Download complete
  5b80453a567d: Pull complete
  3420de6432e1: Pull complete
  65b549a28248: Pull complete
  Digest: sha256:c785e617c8d7015190c0d41af52cc69be8a16e3d9eb7cb21f0bb58bcfca[14](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:14)d6b
  Status: Downloaded newer image for node:lts-alpine
   ---> 97c7a05048e1
  Step 2/6 : RUN apk add --no-cache git python2 build-base
   ---> Running in 03abd6ec1d1d
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    python2 (no such package):
      required by: world[python2]
  The command '/bin/sh -c apk add --no-cache git python2 build-base' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 2.078 seconds before retry.
  /usr/bin/docker build -t 6f[15](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:15)54:c225bc8523c743e7a0fd46ac072d21be -f "/home/runner/work/_actions/borales/actions-yarn/v2.3.0/Dockerfile" "/home/runner/work/_actions/borales/actions-yarn/v2.3.0"
  Sending build context to Docker daemon  7.[16](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:16)8kB
  
  Step 1/6 : FROM node:lts-alpine
   ---> 97c7a05048e1
  Step 2/6 : RUN apk add --no-cache git python2 build-base
   ---> Running in [20](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:20)5aa705ec75
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    python2 (no such package):
      required by: world[python2]
  The command '/bin/sh -c apk add --no-cache git python2 build-base' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 6.716 seconds before retry.
  /usr/bin/docker build -t 6f1554:c225bc8523c743e7a0fd46ac072d[21](https://github.com/IncredibleDevHQ/snappy/runs/6788857739?check_suite_focus=true#step:2:21)be -f "/home/runner/work/_actions/borales/actions-yarn/v2.3.0/Dockerfile" "/home/runner/work/_actions/borales/actions-yarn/v2.3.0"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/6 : FROM node:lts-alpine
   ---> 97c7a05048e1
  Step 2/6 : RUN apk add --no-cache git python2 build-base
   ---> Running in 8a0ba05e16c9
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    python2 (no such package):
      required by: world[python2]
  The command '/bin/sh -c apk add --no-cache git python2 build-base' returned a non-zero code: 1
Error: Docker build failed with exit code 1
##[debug]System.InvalidOperationException: Docker build failed with exit code 1
##[debug]   at GitHub.Runner.Worker.ActionManager.BuildActionContainerAsync(IExecutionContext executionContext, Object data)
##[debug]   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Build borales/actions-yarn@v2.3.0
```

**Comment by captainbrosset** [comment]
Same thing for me since yesterday, and if that helps, here is the action run: https://github.com/captainbrosset/github-engagement-metrics/runs/6785240996?check_suite_focus=true

**Comment by captainbrosset** [comment]
Awesome, it worked for me too. Moved from `v2.3.0` to `v3.0.0`.
Related: [this documentation page](https://github.com/marketplace/actions/github-action-for-yarn) mentions using the `latest` version, but I tried that and it ended up with this error: `Unable to resolve action Borales/actions-yarn@latest, unable to find version latest`.

**Comment by joaquinperezlopez** [comment]
Thx @DDeme, it worked!

**Comment by Borales** [comment]
@captainbrosset I reverted changes to README, doesn't look like github actions know how to use `latest` tag :(
