### ISSUE TITLE
Action Fails for NestJS Build in GH

### ISSUE THREAD

**Issue by ezbeazy** [Borales/actions-yarn#91]
```
$ rimraf dist
$ nest build
/github/workspace/node_modules/loader-runner/lib/LoaderRunner.js:146
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/github/workspace/node_modules/webpack/lib/util/createHash.js:1[44](https://github.com/ELEVATORmedia/elevatorpitch-ts/actions/runs/4078410217/jobs/7028586538#step:6:45):18)
    at BulkUpdateDecorator.update (/github/workspace/node_modules/webpack/lib/util/createHash.js:[46](https://github.com/ELEVATORmedia/elevatorpitch-ts/actions/runs/4078410217/jobs/7028586538#step:6:47):[50](https://github.com/ELEVATORmedia/elevatorpitch-ts/actions/runs/4078410217/jobs/7028586538#step:6:51))
    at RawSource.updateHash (/github/workspace/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/github/workspace/node_modules/webpack/lib/NormalModule.js:835:17)
    at handleParseResult (/github/workspace/node_modules/webpack/lib/NormalModule.js:900:10)
    at /github/workspace/node_modules/webpack/lib/NormalModule.js:991:4
    at processResult (/github/workspace/node_modules/webpack/lib/NormalModule.js:717:11)
    at /github/workspace/node_modules/webpack/lib/NormalModule.js:774:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0
error Command failed with exit code 1.
```

Application builds successfully locally. I thought this was a an issue with my application and Docker however I'm not running node 18.13. I noticed the node version on this repo is "^18.11.18"

**Comment by ezbeazy** [comment]
aahhh v3 no go, v4 go.
